### ISSUE TITLE
Tweepy client and/or mkrichtext formatting bug

### ISSUE THREAD

**Issue by wilddeej** [aurelg/feedspora#34]
I've noticed a few tweets produced by FeedSpora that have incorrect formatting.  An real-life example is:

`AD: New! "Introverts Unite" T-Shirt: #introversion | #unity #causes #activism #satire <link>`

The hashtags are the problematic detail:  this client is configured to only include 4 hashtags, and clearly 5 have been included.  Additionally, the title/hashtag inclusion formatting is funky, using both a colon and a pipe as data separators.
Although minor, this is incorrect and needs resolution (as well as a pertinent test case to detect/report this issue, obviously).

**Comment by aurelg** [comment]
Do you still have the source RSS feed?

**Comment by wilddeej** [comment]
Sort of, although not every item manifests the problem.  It should not be
difficult to reproduce the issue for a mkrichtext and/or TweepyClient test
case, however.

**Comment by wilddeej** [comment]
There are now tests in place that have the same sort of feed formatting that caused the noted problem.  This issue has definitely been fixed, at least with my latest PR for Issue #40
