### ISSUE TITLE
Detailed documentation needed

### ISSUE THREAD

**Issue by wilddeej** [aurelg/feedspora#36]
FeedSpora has a lot of very nice and useful functionality, and as such, needs a good user-oriented document to outline its features and their usage.

**Comment by wilddeej** [comment]
It sounds like a good way to implement this would be to incorporate a wiki.  https://guides.github.com/features/wikis/#creating-your-wiki provides some good information, and https://help.github.com/articles/about-github-wikis/ also seems to be a good resource.
@aurelg if you are OK with setting this up, I'll take on the task of documenting everything I can!

**Comment by aurelg** [comment]
Sorry for the lag. I think you're right: feedspora definitely deserve a better documentation. I'm not so sure about using the github wiki though, as it's bound to github. Don't you think the README.md file would be enough ?

**Comment by wilddeej** [comment]
The README.md is really supposed to be a short introduction to the project (which it currently is, of course).  What I'm envisioning is much larger and beyond the scope of a simple introduction.  I think it would be most useful if it had a section on the common options and their settings, another section for each client with their unique settings (and where/how to find these), maybe even a section each on the two supported feeds, at least to outline where the posted information originates.  That's going to get pretty huge...
If you don't want to go with a Wiki, maybe just a DOCUMENTATION.md would do the trick (although, would that allow linking from one section to another?)

**Comment by aurelg** [comment]
You're right, the documentation shouldn't be in the README. Let's start with the wiki :-)
