### ISSUE TITLE
Feed parser consistency

### ISSUE THREAD

**Issue by aurelg** [aurelg/feedspora#39]
Atom and RSS parsers should support the same set of functionality. Currently, there are differencies, such as `find_rss_image_url`, which is availble for RSS, not for Atom.

**Comment by wilddeej** [comment]
Agreed, but isn't that the only difference at this point?  I think that's a
separate Issue regardless, right?

**Comment by wilddeej** [comment]
Do you know of an Atom feed that contains image data?  I've not been able to find any.

**Comment by aurelg** [comment]
Me neither. Let's wait until we find one, then.

PS: you're right, that's the only difference :-)
