### ISSUE TITLE
add Docker support

### ISSUE THREAD

**Issue by Strubbl** [aurelg/feedspora#5]
Hi Aurélien,

the main purpose of my pull requests is to make feedspora work for me for RSS to Mastodon. And YES, currently feedspora is successfully running on my machine 🎉 

Because i do not want to install all that python stuff on my main machine, I already have created a Dockerfile. But this file is at the moment only local on my disk.
I am willing to share it of course. But currently the problem is, that it is using the Git URLs of my forks of your repositories.

Therefore i am waiting for your feedback back on my PRs and that we merge them. Afterwards i am polishing the Dockerfile i already have and let it point to the repository urls of your account. Finally you'll get another pull request with that file.

I hope that is of interest for you.

Best Regards,
Sven

PS: if you care about, you can assign this issue to me

**Comment by aurelg** [comment]
I do believe a Dockerfile is interesting too :) We'll add it to the repo when you think it's ready :)
