### ISSUE TITLE
LinkedIn support

### ISSUE THREAD

**Issue by wilddeej** [aurelg/feedspora#57]
The LinkedIn client should be enhanced to include functionality for the `post_include_content` and `post_include_media` options (ref. Issue #38).
The existing LinkedIn client implementation uses [python3-linkedin](https://pypi.org/project/python3-linkedin/).  Another alternative might be [python-linkedin](https://github.com/ozgur/python-linkedin).  Depending upon the functionality each provides, the best alternative should be used.

**Comment by aurelg** [comment]
Historically, `python-linkedin` was python2 only. I see it has changed since then. Another element to take into account is the recent API change announced by Linkedin, see [here](https://github.com/DEKHTIARJonathan/python3-linkedin/issues/18).

**Comment by wilddeej** [comment]
Based on what I found in the Issues list for python-linkedin (regarding Python 3 compatibility and other issues) and the fact that the last project submission was on Jun 25, 2015, I think we should stick with python3-linkedin, which seems to be much better maintained.

The upcoming API change is (or will be, more accurately) a definite factor, as there are significant changes to the Share API (which is used to create posts, of course).  It may be necessary to make FeedSpora code updates, based upon what happens within the python3-linkedin dependency.  However, given the timeline for the LinkedIn API/python3-linkedin changes, I think that will need to be a separate/future issue.

**Comment by wilddeej** [comment]
This Issue can be closed out now, right?

**Comment by aurelg** [comment]
Indeed.
